"""HookSkillManager — generates provider-specific hook configs and instruction files.

Bridges the ChatDev orchestration layer with CLI execution layer by translating
provider-agnostic hook definitions (AgentHooksConfig) into the format expected by
each CLI provider (Claude Code, Gemini CLI, Copilot CLI).

Lifecycle:
    1. ``generate()`` — writes hook config + instruction files to workspace before agent runs
    2. ``cleanup()``  — restores/removes generated files after agent completes
"""

import json
import logging
import os
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from entity.configs.node.hooks import AgentHooksConfig, HookHandler, HookMatcher, SubAgentConfig, HOOK_EVENTS

logger = logging.getLogger(__name__)

# Regex for $ENV{VAR_NAME} placeholders (same pattern as cli_provider_base.py)
_ENV_PLACEHOLDER = re.compile(r"\$ENV\{([A-Za-z0-9_]+)\}")


def _resolve_env_in_mcp_servers(servers: Dict[str, Any]) -> Dict[str, Any]:
    """Resolve $ENV{VAR_NAME} placeholders in MCP server config using os.environ.

    Recursively walks the dict, replacing $ENV{X} with os.environ["X"].
    Unresolved placeholders are left as-is (the CLI will resolve them at runtime).
    """
    import copy
    result = copy.deepcopy(servers)
    for server_name, server_cfg in result.items():
        if not isinstance(server_cfg, dict):
            continue
        _resolve_env_recursive(server_cfg)
    return result


def _resolve_env_recursive(obj: Any) -> None:
    """In-place resolve $ENV{} placeholders in a nested dict/list structure."""
    if isinstance(obj, dict):
        for key in list(obj.keys()):
            val = obj[key]
            if isinstance(val, str):
                obj[key] = _resolve_env_str(val)
            elif isinstance(val, (dict, list)):
                _resolve_env_recursive(val)
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            if isinstance(item, str):
                obj[i] = _resolve_env_str(item)
            elif isinstance(item, (dict, list)):
                _resolve_env_recursive(item)


def _resolve_env_str(value: str) -> str:
    """Replace $ENV{VAR} with os.environ value. Leave as-is if not found."""
    def replacer(m: re.Match) -> str:
        var_name = m.group(1)
        return os.environ.get(var_name, m.group(0))
    return _ENV_PLACEHOLDER.sub(replacer, value)


# Event name mapping: ChatDev (provider-agnostic) → Provider-specific
EVENT_MAP_GEMINI = {
    "PreToolUse": "BeforeTool",
    "PostToolUse": "AfterTool",
    "PostToolUseFailure": "AfterToolFailure",
    "Stop": "AfterAgent",
    "SessionStart": "SessionStart",
    "SessionEnd": "SessionEnd",
    "PreCompact": "PreCompress",
    "UserPromptSubmit": "BeforePrompt",
    "Notification": "Notification",
    "SubagentStart": "SubagentStart",
    "SubagentStop": "SubagentStop",
}

EVENT_MAP_COPILOT = {
    "PreToolUse": "preToolUse",
    "PostToolUse": "postToolUse",
    "PostToolUseFailure": "postToolUseFailure",
    "Stop": "sessionEnd",
    "SessionStart": "sessionStart",
    "SessionEnd": "sessionEnd",
    "UserPromptSubmit": "userPromptSubmit",
    "Notification": "notification",
    "SubagentStart": "subagentStart",
    "SubagentStop": "subagentStop",
}


@dataclass
class GeneratedFiles:
    """Tracks files generated by HookSkillManager for cleanup."""

    hook_config_path: Optional[str] = None
    hook_config_backup: Optional[str] = None  # Previous config if it existed
    instruction_path: Optional[str] = None
    instruction_was_created: bool = False  # True = we created it, cleanup should remove
    copilot_hook_files: List[str] = field(default_factory=list)  # Copilot uses separate files
    sub_agent_files: List[str] = field(default_factory=list)  # Sub-agent MD files we created


class HookSkillManager:
    """Generates and manages hook/instruction files for CLI providers."""

    def generate(
        self,
        provider_type: str,
        hooks_config: Optional[AgentHooksConfig],
        instructions_file: Optional[str],
        workspace_dir: str,
        node_id: str,
        sub_agents: Optional[List[SubAgentConfig]] = None,
    ) -> GeneratedFiles:
        """Generate provider-specific hook config, instruction, and sub-agent files.

        Args:
            provider_type: Provider name ("claude-code", "gemini-cli", "copilot-cli")
            hooks_config: Provider-agnostic hook definitions (or None)
            instructions_file: Path to source instruction MD file (or None)
            workspace_dir: Agent workspace directory
            node_id: Node ID for namespacing
            sub_agents: List of sub-agent configs to deploy (or None)

        Returns:
            GeneratedFiles tracking what was created for cleanup.
        """
        result = GeneratedFiles()

        # 1. Instruction file
        if instructions_file:
            src_path = self._resolve_instructions_source(instructions_file, workspace_dir)
            if src_path and os.path.isfile(src_path):
                target = self._get_instruction_target(provider_type, workspace_dir, node_id)
                result.instruction_was_created = self._write_instruction_file(target, src_path)
                if result.instruction_was_created:
                    result.instruction_path = target

        # 2. Hook config
        if hooks_config and hooks_config.has_hooks():
            if provider_type == "claude-code":
                path, backup = self._generate_claude_hooks(hooks_config, workspace_dir)
                result.hook_config_path = path
                result.hook_config_backup = backup
            elif provider_type == "gemini-cli":
                path, backup = self._generate_gemini_hooks(hooks_config, workspace_dir)
                result.hook_config_path = path
                result.hook_config_backup = backup
            elif provider_type == "copilot-cli":
                files = self._generate_copilot_hooks(hooks_config, workspace_dir)
                result.copilot_hook_files = files

        # 3. Sub-agent files
        if sub_agents:
            result.sub_agent_files = self._generate_sub_agents(
                provider_type, sub_agents, workspace_dir
            )

        return result

    def cleanup(self, files: GeneratedFiles) -> None:
        """Remove or restore generated files after agent completes."""
        # Restore hook config backup or remove generated config
        if files.hook_config_backup and files.hook_config_path:
            try:
                shutil.move(files.hook_config_backup, files.hook_config_path)
            except OSError as e:
                logger.warning("Failed to restore hook config backup: %s", e)
        elif files.hook_config_path:
            try:
                os.remove(files.hook_config_path)
            except OSError:
                pass

        # Remove copilot hook files
        for path in files.copilot_hook_files:
            try:
                os.remove(path)
            except OSError:
                pass

        # Remove sub-agent files we created
        for path in files.sub_agent_files:
            try:
                os.remove(path)
            except OSError:
                pass

        # Remove instruction file only if we created it
        if files.instruction_was_created and files.instruction_path:
            try:
                os.remove(files.instruction_path)
                # Clean up empty parent dirs
                parent = os.path.dirname(files.instruction_path)
                while parent:
                    try:
                        os.rmdir(parent)  # Only removes if empty
                        parent = os.path.dirname(parent)
                    except OSError:
                        break
            except OSError:
                pass

    # ------------------------------------------------------------------
    # Instruction file helpers
    # ------------------------------------------------------------------

    def _resolve_instructions_source(
        self, instructions_file: str, workspace_dir: str
    ) -> Optional[str]:
        """Resolve instruction file path (absolute or relative to project root)."""
        if os.path.isabs(instructions_file):
            return instructions_file
        # Try relative to the ChatDev project root (parent of runtime/)
        project_root = str(Path(__file__).resolve().parents[4])
        candidate = os.path.join(project_root, instructions_file)
        if os.path.isfile(candidate):
            return candidate
        # Try relative to workspace
        candidate = os.path.join(workspace_dir, instructions_file)
        if os.path.isfile(candidate):
            return candidate
        return None

    def _get_instruction_target(
        self, provider_type: str, workspace_dir: str, node_id: str
    ) -> str:
        """Get the target path for instruction file based on provider type."""
        safe_id = node_id.replace(" ", "-").lower()
        if provider_type == "claude-code":
            return os.path.join(workspace_dir, ".claude", "skills", safe_id, "SKILL.md")
        elif provider_type == "gemini-cli":
            return os.path.join(workspace_dir, "GEMINI.md")
        elif provider_type == "copilot-cli":
            return os.path.join(workspace_dir, ".github", "copilot-instructions.md")
        else:
            return os.path.join(workspace_dir, f".chatdev-instructions-{safe_id}.md")

    def _write_instruction_file(self, target: str, source: str) -> bool:
        """Write instruction file to target. Does NOT overwrite existing files.

        Returns True if file was created (and should be cleaned up).
        """
        if os.path.exists(target):
            logger.info("Instruction file already exists, preserving: %s", target)
            return False
        try:
            os.makedirs(os.path.dirname(target), exist_ok=True)
            shutil.copy2(source, target)
            logger.debug("Created instruction file: %s", target)
            return True
        except OSError as e:
            logger.warning("Failed to create instruction file %s: %s", target, e)
            return False

    # ------------------------------------------------------------------
    # Claude Code hooks
    # ------------------------------------------------------------------

    def _generate_claude_hooks(
        self, config: AgentHooksConfig, workspace_dir: str
    ) -> tuple:
        """Generate Claude Code .claude/settings.local.json hooks section.

        Returns (config_path, backup_path_or_None).
        """
        hooks_dict: Dict[str, list] = {}
        for event_name in HOOK_EVENTS:
            matchers = getattr(config, event_name, [])
            if not matchers:
                continue
            hooks_dict[event_name] = [
                self._matcher_to_claude(m) for m in matchers
            ]

        path = os.path.join(workspace_dir, ".claude", "settings.local.json")
        backup = None

        if os.path.exists(path):
            backup = path + ".chatdev_backup"
            try:
                shutil.copy2(path, backup)
                with open(path) as f:
                    existing = json.load(f)
                existing.setdefault("hooks", {}).update(hooks_dict)
                settings = existing
            except (json.JSONDecodeError, OSError):
                settings = {"hooks": hooks_dict}
        else:
            settings = {"hooks": hooks_dict}

        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            json.dump(settings, f, indent=2)
        logger.debug("Generated Claude Code hooks: %s", path)
        return path, backup

    def _matcher_to_claude(self, matcher: HookMatcher) -> dict:
        """Convert a HookMatcher to Claude Code format."""
        entry: Dict[str, Any] = {}
        if matcher.matcher:
            entry["matcher"] = matcher.matcher
        entry["hooks"] = [self._handler_to_claude(h) for h in matcher.hooks]
        return entry

    @staticmethod
    def _handler_to_claude(handler: HookHandler) -> dict:
        """Convert a HookHandler to Claude Code hook format."""
        result: Dict[str, Any] = {"type": handler.type}
        if handler.type == "command" and handler.command:
            result["command"] = handler.command
        elif handler.type in ("prompt", "agent") and handler.prompt:
            result["prompt"] = handler.prompt
        if handler.timeout is not None:
            result["timeout"] = handler.timeout
        if handler.model:
            result["model"] = handler.model
        # Claude Code extended hook features
        if handler.async_hook:
            result["async"] = True
        if handler.once:
            result["once"] = True
        if handler.status_message:
            result["statusMessage"] = handler.status_message
        return result

    # ------------------------------------------------------------------
    # Gemini CLI hooks
    # ------------------------------------------------------------------

    def _generate_gemini_hooks(
        self, config: AgentHooksConfig, workspace_dir: str
    ) -> tuple:
        """Generate Gemini CLI .gemini/settings.json hooks section.

        Gemini only supports command-type hooks.  Prompt hooks are converted
        to command hooks using the prompt-hook-wrapper.py script.

        Returns (config_path, backup_path_or_None).
        """
        hooks_list: List[Dict[str, Any]] = []
        for chatdev_event, gemini_event in EVENT_MAP_GEMINI.items():
            matchers = getattr(config, chatdev_event, [])
            for m in matchers:
                for h in m.hooks:
                    handler = self._handler_to_gemini(h, gemini_event, m.matcher)
                    if handler:
                        hooks_list.append(handler)

        path = os.path.join(workspace_dir, ".gemini", "settings.json")
        backup = None

        if os.path.exists(path):
            backup = path + ".chatdev_backup"
            try:
                shutil.copy2(path, backup)
                with open(path) as f:
                    existing = json.load(f)
                existing.setdefault("hooks", []).extend(hooks_list)
                settings = existing
            except (json.JSONDecodeError, OSError):
                settings = {"hooks": hooks_list}
        else:
            settings = {"hooks": hooks_list}

        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            json.dump(settings, f, indent=2)
        logger.debug("Generated Gemini CLI hooks: %s", path)
        return path, backup

    def _handler_to_gemini(
        self, handler: HookHandler, gemini_event: str, matcher: str
    ) -> Optional[dict]:
        """Convert a HookHandler to Gemini CLI hook format."""
        entry: Dict[str, Any] = {"event": gemini_event}
        if matcher:
            entry["toolNameRegex"] = matcher

        if handler.type == "command" and handler.command:
            entry["command"] = handler.command
        elif handler.type in ("prompt", "agent"):
            # Gemini doesn't support prompt hooks — use wrapper script
            wrapper = self._get_hooks_dir() / "prompt-hook-wrapper.py"
            if wrapper.exists():
                entry["command"] = f"python {wrapper}"
                # Pass verdict keywords if the prompt mentions them
                keywords = self._extract_keywords_from_prompt(handler.prompt or "")
                if keywords:
                    entry.setdefault("env", {})["VERDICT_KEYWORDS"] = ",".join(keywords)
            else:
                logger.warning("prompt-hook-wrapper.py not found, skipping prompt hook")
                return None
        else:
            return None

        if handler.timeout is not None:
            entry["timeout"] = handler.timeout
        return entry

    # ------------------------------------------------------------------
    # Copilot CLI hooks
    # ------------------------------------------------------------------

    def _generate_copilot_hooks(
        self, config: AgentHooksConfig, workspace_dir: str
    ) -> List[str]:
        """Generate Copilot CLI .github/hooks/*.json files.

        Each hook is a separate JSON file. Returns list of created file paths.
        """
        hooks_dir = os.path.join(workspace_dir, ".github", "hooks")
        os.makedirs(hooks_dir, exist_ok=True)
        created_files: List[str] = []

        for chatdev_event, copilot_event in EVENT_MAP_COPILOT.items():
            matchers = getattr(config, chatdev_event, [])
            for i, m in enumerate(matchers):
                for j, h in enumerate(m.hooks):
                    hook_data = self._handler_to_copilot(h, copilot_event, m.matcher)
                    if hook_data:
                        hook_file = os.path.join(
                            hooks_dir, f"chatdev-{copilot_event}-{i}-{j}.json"
                        )
                        with open(hook_file, "w") as f:
                            json.dump(hook_data, f, indent=2)
                        created_files.append(hook_file)

        if created_files:
            logger.debug("Generated %d Copilot CLI hook files", len(created_files))
        return created_files

    def _handler_to_copilot(
        self, handler: HookHandler, copilot_event: str, matcher: str
    ) -> Optional[dict]:
        """Convert a HookHandler to Copilot CLI hook format."""
        entry: Dict[str, Any] = {"event": copilot_event}
        if matcher:
            entry["toolNamePattern"] = matcher

        if handler.type == "command" and handler.command:
            entry["bash"] = handler.command
        elif handler.type in ("prompt", "agent"):
            # Copilot doesn't support prompt hooks — use wrapper script
            wrapper = self._get_hooks_dir() / "prompt-hook-wrapper.py"
            if wrapper.exists():
                keywords = self._extract_keywords_from_prompt(handler.prompt or "")
                env_prefix = ""
                if keywords:
                    env_prefix = f"VERDICT_KEYWORDS='{','.join(keywords)}' "
                entry["bash"] = f"{env_prefix}python {wrapper}"
            else:
                logger.warning("prompt-hook-wrapper.py not found, skipping prompt hook")
                return None
        else:
            return None

        entry["timeoutSec"] = handler.timeout or 30
        return entry

    # ------------------------------------------------------------------
    # Sub-agent file generation
    # ------------------------------------------------------------------

    def _generate_sub_agents(
        self, provider_type: str, sub_agents: List[SubAgentConfig], workspace_dir: str
    ) -> List[str]:
        """Generate sub-agent MD files in the provider-specific directory.

        Returns list of file paths that were created (for cleanup).
        """
        created: List[str] = []
        for agent_cfg in sub_agents:
            source_path = self._resolve_instructions_source(agent_cfg.source, workspace_dir)
            if not source_path or not os.path.isfile(source_path):
                logger.warning(
                    "Sub-agent source not found: %s (agent: %s)", agent_cfg.source, agent_cfg.name
                )
                continue

            target = self._get_sub_agent_target(provider_type, workspace_dir, agent_cfg.name)
            if os.path.exists(target):
                logger.info("Sub-agent file already exists, preserving: %s", target)
                continue

            try:
                os.makedirs(os.path.dirname(target), exist_ok=True)
                content = self._read_file(source_path)
                # Transform frontmatter for the target provider
                transformed = self._transform_sub_agent_content(provider_type, content, agent_cfg)
                with open(target, "w") as f:
                    f.write(transformed)
                created.append(target)
                logger.debug("Created sub-agent file: %s", target)
            except OSError as e:
                logger.warning("Failed to create sub-agent file %s: %s", target, e)

        if created:
            logger.debug("Generated %d sub-agent files for %s", len(created), provider_type)
        return created

    @staticmethod
    def _get_sub_agent_target(provider_type: str, workspace_dir: str, name: str) -> str:
        """Get provider-specific sub-agent file path."""
        if provider_type == "claude-code":
            return os.path.join(workspace_dir, ".claude", "agents", f"{name}.md")
        elif provider_type == "gemini-cli":
            return os.path.join(workspace_dir, ".gemini", "agents", f"{name}.md")
        elif provider_type == "copilot-cli":
            return os.path.join(workspace_dir, ".github", "agents", f"{name}.md")
        else:
            return os.path.join(workspace_dir, ".chatdev", "agents", f"{name}.md")

    def _transform_sub_agent_content(
        self, provider_type: str, content: str, agent_cfg: SubAgentConfig
    ) -> str:
        """Transform sub-agent MD content for the target provider.

        The source files use a generic YAML frontmatter. This method rewrites
        the frontmatter to match what each CLI provider expects.
        """
        # Parse frontmatter and body
        frontmatter, body = self._split_frontmatter(content)

        if provider_type == "claude-code":
            return self._format_claude_sub_agent(frontmatter, body, agent_cfg)
        elif provider_type == "gemini-cli":
            return self._format_gemini_sub_agent(frontmatter, body, agent_cfg)
        elif provider_type == "copilot-cli":
            return self._format_copilot_sub_agent(frontmatter, body, agent_cfg)
        else:
            return content  # Passthrough

    @staticmethod
    def _split_frontmatter(content: str) -> tuple:
        """Split YAML frontmatter from markdown body.

        Returns (frontmatter_dict, body_str).
        """
        import yaml

        if not content.startswith("---"):
            return {}, content

        parts = content.split("---", 2)
        if len(parts) < 3:
            return {}, content

        try:
            fm = yaml.safe_load(parts[1]) or {}
        except Exception:
            fm = {}
        body = parts[2].lstrip("\n")
        return fm, body

    @staticmethod
    def _format_claude_sub_agent(fm: dict, body: str, cfg: SubAgentConfig) -> str:
        """Format for Claude Code: .claude/agents/{name}.md"""
        import yaml

        lines = ["---"]
        lines.append(f"name: {fm.get('name', cfg.name)}")
        lines.append(f"description: {fm.get('description', cfg.description)}")
        # Tools: YAML config overrides source frontmatter
        tools = cfg.tools if cfg.tools else fm.get("tools", [])
        if isinstance(tools, list) and tools:
            lines.append(f"tools: {', '.join(tools)}")
        # Disallowed tools (Claude Code specific)
        disallowed = cfg.disallowed_tools
        if disallowed:
            lines.append(f"disallowedTools: {', '.join(disallowed)}")
        # Model: YAML config overrides source frontmatter
        model = cfg.model or fm.get("model")
        if model:
            lines.append(f"model: {model}")
        # Max turns: YAML config overrides source frontmatter
        max_turns = cfg.max_turns or fm.get("maxTurns") or fm.get("max_turns")
        if max_turns:
            lines.append(f"maxTurns: {max_turns}")
        # MCP servers: YAML config overrides source frontmatter
        mcp_servers = cfg.mcp_servers if cfg.mcp_servers else fm.get("mcpServers", {})
        if mcp_servers:
            # Resolve $ENV{} placeholders from os.environ
            resolved = _resolve_env_in_mcp_servers(mcp_servers)
            mcp_yaml = yaml.dump({"mcpServers": resolved}, default_flow_style=False).rstrip()
            lines.append(mcp_yaml)
        lines.append("---")
        lines.append("")
        lines.append(body)
        return "\n".join(lines)

    # Gemini tool name mapping (ChatDev/Claude names → Gemini equivalents)
    GEMINI_TOOL_MAP = {
        "Read": "read_file",
        "Grep": "grep_search",
        "Glob": "list_directory",
        "Write": "write_file",
        "Edit": "edit_file",
        "WebFetch": "web_fetch",
        "WebSearch": "web_search",
        "Bash": "shell",
    }

    # Gemini model name mapping
    GEMINI_MODEL_MAP = {
        "haiku": "gemini-2.5-flash",
        "sonnet": "gemini-2.5-pro",
        "opus": "gemini-2.5-pro",
    }

    @classmethod
    def _format_gemini_sub_agent(cls, fm: dict, body: str, cfg: SubAgentConfig) -> str:
        """Format for Gemini CLI: .gemini/agents/{name}.md"""
        lines = ["---"]
        lines.append(f"name: {fm.get('name', cfg.name)}")
        lines.append(f"description: {fm.get('description', cfg.description)}")
        tools = cfg.tools if cfg.tools else fm.get("tools", [])
        if isinstance(tools, list) and tools:
            gemini_tools = [cls.GEMINI_TOOL_MAP.get(t, t) for t in tools]
            lines.append(f"tools: [{', '.join(gemini_tools)}]")
        # Model mapping for Gemini
        model = cfg.model or fm.get("model")
        if model:
            gemini_model = cls.GEMINI_MODEL_MAP.get(model, model)
            lines.append(f"model: {gemini_model}")
        # Max turns
        max_turns = cfg.max_turns or fm.get("maxTurns") or fm.get("max_turns")
        if max_turns:
            lines.append(f"max_turns: {max_turns}")
        lines.append("---")
        lines.append("")
        lines.append(body)
        return "\n".join(lines)

    # Copilot model name mapping
    COPILOT_MODEL_MAP = {
        "haiku": "claude-haiku-4-5",
        "sonnet": "claude-sonnet-4-5",
        "opus": "claude-opus-4",
    }

    @classmethod
    def _format_copilot_sub_agent(cls, fm: dict, body: str, cfg: SubAgentConfig) -> str:
        """Format for Copilot CLI: .github/agents/{name}.md"""
        lines = ["---"]
        lines.append(f"name: {fm.get('name', cfg.name)}")
        lines.append(f"description: {fm.get('description', cfg.description)}")
        tools = cfg.tools if cfg.tools else fm.get("tools", [])
        if isinstance(tools, list) and tools:
            lines.append(f"tools: {', '.join(tools)}")
        # Model mapping for Copilot
        model = cfg.model or fm.get("model")
        if model:
            copilot_model = cls.COPILOT_MODEL_MAP.get(model, model)
            lines.append(f"model: {copilot_model}")
        lines.append("---")
        lines.append("")
        lines.append(body)
        return "\n".join(lines)

    @staticmethod
    def _read_file(path: str) -> str:
        """Read file content as string."""
        with open(path) as f:
            return f.read()

    # ------------------------------------------------------------------
    # Utility helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _get_hooks_dir() -> Path:
        """Get the .chatdev/hooks/ directory path."""
        return Path(__file__).resolve().parents[4] / ".chatdev" / "hooks"

    @staticmethod
    def _extract_keywords_from_prompt(prompt: str) -> List[str]:
        """Extract verdict keywords from a prompt hook's text.

        Looks for patterns like REVIEW_PASS, REVIEW_FAIL, QA_PASS, QA_FAIL, etc.
        """
        import re
        # Match uppercase words with underscores that look like verdict keywords
        pattern = r'\b([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+)\b'
        matches = re.findall(pattern, prompt)
        # Filter to likely verdict keywords (contain PASS, FAIL, APPROVE, etc.)
        verdict_indicators = {"PASS", "FAIL", "APPROVE", "REJECT", "EXIT"}
        keywords = []
        seen = set()
        for m in matches:
            if m in seen:
                continue
            parts = set(m.split("_"))
            if parts & verdict_indicators:
                keywords.append(m)
                seen.add(m)
        return keywords
